import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  containerView: {
    backgroundColor: '#2a2a2a',
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
  },
  titleView: {
    flex: 1,
    backgroundColor: '#2a2a2a',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  moveView: {
    flex: 0.5,
    backgroundColor: '#2a2a2a',
    marginBottom: 50,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 50,
    letterSpacing: 6,
    textShadowColor: '#000',
    textShadowRadius: 2,
  },
  gameBoardView: {
    flex: 2,
    backgroundColor: '#9b7474',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#363535',
    padding: 10,
    margin: 50,
    marginBottom: 10,
    marginTop: 10,
    borderRadius: 12,
    display: 'flex',
    flexDirection: 'column',
  },
  button: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#c4c4c4',
    padding: 0,
    paddingLeft: 30,
    paddingRight: 30,
    borderRadius: 55,
  },
  moveBtn: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 0,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 55,
    marginLeft: 10,
    marginRight: 10,
  },
  btnText: {
    color: '#2a2a2a',
    fontWeight: 'bold',
    fontSize: 50,
  },
});
